const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateIST=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(d),time=d=>d&&Number.isFinite(Date.parse(d))?new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(d)):'Time not supplied';
const link=(url,label)=>{try{const u=new URL(url);return /^https?:$/.test(u.protocol)?`<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`:''}catch{return ''}};
let data=null,sport='All',busy=false,target=2,ticketRequest=0;
$('dateFilter').value=dateIST(new Date());
async function api(path,body){const r=await fetch(path,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(65000)});const d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
const query=()=>`date=${$('dateFilter').value}`;
const empty=(title,copy)=>`<div class="empty-state"><h3>${esc(title)}</h3><p>${esc(copy)}</p></div>`;
const titles={dashboard:['The match desk','Live source data. Match context. Clear gaps.'],analysis:['Ask the desk','Research grounded in your connected sources.'],multipliers:['The multiplier lab','Explore payout combinations from fresh Stake prices.'],sources:['The source monitor','Connection health, coverage and collection times.'],connections:['Your connections','Private credentials. Explicit connection status.']};
function route(){const view=location.hash.slice(1) in titles?location.hash.slice(1):'dashboard';document.querySelectorAll('[data-panel]').forEach(el=>el.hidden=el.dataset.panel!==view);document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view));$('pageTitle').innerHTML=esc(titles[view][0])+'<span>.</span>';$('pageSubtitle').textContent=titles[view][1];$('viewName').textContent=view.toUpperCase();if(view==='multipliers')loadTickets()}
window.addEventListener('hashchange',route);
function renderMatches(){if(!data)return;const q=$('searchInput').value.toLowerCase(),state=$('stateFilter').value,window=$('windowFilter').value;const day=$('dateFilter').value,next=dateIST(new Date(Date.parse(day+'T12:00:00Z')+86400000));const events=data.events.filter(e=>(sport==='All'||e.sport===sport)&&(!q||`${e.name} ${e.league}`.toLowerCase().includes(q))&&(state==='all'||e.state===state)&&(window==='both'||(e.start?dateIST(new Date(e.start)):e.date)===(window==='today'?day:next)));
$('visibleCount').textContent=`${events.length} EVENTS`;$('matchList').innerHTML=events.length?events.map(e=>`<article class="match-row"><div><div class="match-label"><span class="sport-tag">${esc(e.sport)}</span><span>${esc(e.league)}</span>${e.official?'<span class="official-tag">OFFICIAL</span>':''}</div><h3>${esc(e.name)}</h3><div class="match-note">${esc((e.competitors||[]).filter(c=>c.score!==null&&c.score!==undefined).map(c=>`${c.name}: ${c.score}`).join(' · ')||e.venue||e.status)}</div><div class="match-note">${esc((e.competitors||[]).filter(c=>c.starter).map(c=>`${c.starter} (probable)`).join(' · '))}</div></div><div class="match-time">${esc(e.start?time(e.start):e.date||'Time unknown')}<small class="${e.state==='live'?'live-label':''}">${esc(e.status)}${e.feed_status==='stale'?' · STALE':''}</small></div><button class="match-action" data-event="${esc(e.id)}" aria-label="Details for ${esc(e.name)}">↗</button></article>`).join(''):empty('No matches in this filter','Check the Source monitor to distinguish an empty schedule from an unavailable feed.');
const news=data.news.filter(n=>sport==='All'||n.sport===sport||(sport==='WTA'&&n.sport==='ATP')).slice(0,15);$('newsList').innerHTML=news.length?news.map(n=>`<article class="news-item"><span>${esc(n.sport)} / ${esc(n.source)}${n.official?' / OFFICIAL':''}</span>${link(n.url,n.title)}<small>${esc(time(n.published_at))}${n.feed_status==='stale'?' · STALE':''}</small></article>`).join(''):empty('No headlines returned','Try another sport or check source health.');}
function render(){const good=data.sources.filter(s=>s.status==='connected').length;$('eventMetric').textContent=data.events.length;$('sourceMetric').textContent=`${good}/${data.sources.length}`;$('sourceSub').textContent='Responding sources; coverage varies';$('oddsMetric').textContent=data.odds.selections.length;$('oddsSub').textContent=data.odds.status;$('auraMetric').textContent=data.aura.status==='connected'?'Online':'Offline';$('auraSub').textContent=data.aura.message;$('globalStatus').textContent=good?'FEEDS UPDATED · PARTIAL COVERAGE':'SOURCES UNAVAILABLE';$('globalLed').classList.toggle('active',good>0);$('refreshTime').textContent=`Collected ${time(data.generated_at)} IST`;$('coverageTitle').textContent=`${good} sources responding`;$('coverageText').textContent=`${data.sources.length-good} sources unavailable or disconnected. Injury and lineup completeness varies by match. Open a match dossier before using its data.`;
const sports=['All','MLB','NPB','KBO','ATP','WTA','NBA','NFL','NHL','Cricket','Soccer','Esports'];$('sportFilters').innerHTML=sports.map(s=>`<button data-sport="${s}" class="${sport===s?'active':''}" aria-pressed="${sport===s}">${s} <small>${s==='All'?data.events.length:data.events.filter(e=>e.sport===s).length}</small></button>`).join('');
$('sourceCount').textContent=`${good} RESPONDING`;$('sourceList').innerHTML=data.sources.map(s=>`<article class="source-row"><div><strong>${esc(s.name)}</strong><small>${esc(s.sport)} · ${s.official?'Official':'Secondary/provider'}</small>${link(s.url,'Original source')}</div><div class="source-features">${esc((s.features||[]).join(' · '))}<small>${s.event_count} events · ${s.news_count} headlines</small></div><div><span class="source-status ${esc(s.status)}">${esc(s.status)}${s.partial?' · partial':''}</span><small>Collected: ${esc(time(s.received_at))}</small>${s.error?`<p class="source-error">${esc(s.error)}</p>`:''}</div></article>`).join('');$('stakeConnectionStatus').textContent=data.odds.message;$('auraConnectionStatus').textContent=data.aura.message;for(const id of ['oddsForm','auraForm'])$(id).hidden=!data.connections.can_save;renderMatches();}
async function load(){if(busy)return;busy=true;$('refreshButton').disabled=true;$('loadingBanner').hidden=!!data;try{data=await api('/api/dashboard?'+query());$('errorBanner').hidden=true;render()}catch(e){$('errorBanner').hidden=false;$('errorBanner').textContent=`Refresh failed: ${e.message}. ${data?'Previously displayed data may be stale.':'Check that the ATLAS server is running.'}`;$('globalStatus').textContent='REFRESH FAILED'}finally{busy=false;$('loadingBanner').hidden=true;$('refreshButton').disabled=false}}
function ticketHTML(t){return `<article class="ticket"><div class="ticket-head"><span>${t.legs.length} LEGS</span><strong>${t.total_odds.toFixed(2)}×</strong></div>${t.legs.map(s=>`<div class="ticket-leg"><div><b>${esc(s.selection)}</b><small>${esc(s.event)} · ${esc(s.market)}</small></div><strong>${s.odds.toFixed(2)}</strong></div>`).join('')}<p>Break-even ${(100/t.total_odds).toFixed(2)}% · not a win forecast.</p>${t.legs.map(s=>link(s.source_url,'Stake market')).join(' ')}<small>Prices checked ${esc(time(t.legs[0]?.updated_at))}</small></article>`}
async function loadTickets(){const request=++ticketRequest;$('multiplierTabs').innerHTML=[2,3,4,5,10,20,100,1000].map(t=>`<button data-target="${t}" class="${t===target?'active':''}">${t}×</button>`).join('');$('targetValue').innerHTML=target+'<span>×</span>';$('targetProbability').textContent=`${+(100/target).toFixed(2)}%`;$('targetOptions').textContent=target<=5?5:3;$('ticketStatus').textContent='Checking fresh Stake prices…';try{const d=await api(`/api/tickets?${query()}&target=${target}`);if(request!==ticketRequest)return;$('ticketStatus').textContent=`${d.message} ${d.feed_message||''}`;$('tickets').innerHTML=d.options.length?d.options.map(ticketHTML).join(''):empty('No verified combinations available','Add a provider key with Stake coverage in Connections. Options will appear only when enough fresh prices qualify.')}catch(e){if(request===ticketRequest)$('ticketStatus').textContent=e.message}}
$('askForm').addEventListener('submit',async e=>{e.preventDefault();const message=$('askInput').value.trim();if(!message)return;const log=$('conversationLog');log.insertAdjacentHTML('beforeend',`<div class="user-message"><p>${esc(message)}</p></div>`);$('askInput').value='';$('askSubmit').disabled=true;try{const d=await api('/api/ask',{message,date:$('dateFilter').value,use_aura:$('useAura').checked});log.insertAdjacentHTML('beforeend',`<div class="assistant-message"><span>ATLAS · ${esc(time(d.generated_at))}</span><p>${esc(d.text)}</p>${(d.singles||[]).map(s=>`<p><b>${esc(s.selection)} · ${s.odds.toFixed(2)}</b><br>${esc(s.event)} / ${esc(s.market)}<br>${link(s.source_url,'Stake market')} · ${esc(time(s.updated_at))}</p>`).join('')}${d.tickets?.options.map(ticketHTML).join('')||''}${d.aura?`<div class="aura-response"><b>AURA · ${esc(d.aura.status)}</b><p>${esc(d.aura.text)}</p></div>`:''}</div>`)}catch(err){log.insertAdjacentHTML('beforeend',`<div class="assistant-message"><p>${esc(err.message)}</p></div>`)}finally{$('askSubmit').disabled=false;log.scrollTop=log.scrollHeight}});
async function openEvent(id){$('eventDialog').showModal();$('eventDetails').innerHTML=empty('Loading match context','Checking the original source…');try{const d=await api(`/api/event?${query()}&id=${encodeURIComponent(id)}`),e=d.event;$('eventDetails').innerHTML=`<div class="dossier"><span class="eyebrow">${esc(e.sport)} / ${esc(e.source)}</span><h2>${esc(e.name)}</h2><p>${esc(time(e.start))} · ${esc(e.status)}</p><div class="dossier-grid"><div class="dossier-fact"><small>FEED COLLECTED</small><strong>${esc(time(e.received_at))}</strong></div><div class="dossier-fact"><small>VENUE</small><strong>${esc(e.venue||'Not supplied')}</strong></div></div><h3>Starting players / lineups</h3>${d.lineups?.map(l=>`<p><b>${esc(l.team)} · ${esc(l.status)}</b><br>${esc(l.players.join(', '))}</p>`).join('')||'<p>Confirmed lineups not supplied by this adapter.</p>'}<h3>Probable starters</h3><p>${esc((e.competitors||[]).filter(c=>c.starter).map(c=>`${c.name}: ${c.starter} (probable)`).join(' · ')||'Not supplied')}</p><h3>Injury information</h3><p>${d.injuries?.length?esc(JSON.stringify(d.injuries).slice(0,5000)):'No verified injury report supplied. This does not mean injury-free.'}</p>${d.weather?`<h3>Weather</h3><p>${esc(Object.entries(d.weather).map(([k,v])=>`${k}: ${v}`).join(' · '))}</p>`:''}<p>${esc([...(e.notes||[]),...(d.notes||[])].join(' '))}</p>${link(d.source_url||e.source_url,'Open original match report')}</div>`}catch(e){$('eventDetails').innerHTML=empty('Details unavailable',e.message)}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.sport){sport=b.dataset.sport;render()}if(b.dataset.target){target=Number(b.dataset.target);loadTickets()}if(b.dataset.prompt){location.hash='analysis';$('askInput').value=b.dataset.prompt;$('askForm').requestSubmit()}if(b.dataset.event)openEvent(b.dataset.event)});
$('closeEvent').onclick=()=>$('eventDialog').close();$('refreshButton').onclick=load;$('dateFilter').onchange=()=>{load();if(location.hash==='#multipliers')loadTickets()};for(const id of ['searchInput','stateFilter','windowFilter'])$(id).addEventListener('input',renderMatches);
for(const [form,input,key]of [['oddsForm','oddsKey','odds_key'],['auraForm','auraToken','aura_token']])$(form).addEventListener('submit',async e=>{e.preventDefault();if(!$(input).value.trim())return;try{const d=await api('/api/connections',{[key]:$(input).value});$(input).value='';$('connectionFeedback').textContent=d.message;load()}catch(err){$('connectionFeedback').textContent=err.message}finally{$('connectionFeedback').hidden=false}});
let motion=localStorage.getItem('atlas-motion')!=='off';function motionState(){document.body.classList.toggle('no-motion',!motion);$('motionButton').textContent=motion?'MOTION ON':'MOTION OFF';$('motionButton').setAttribute('aria-pressed',String(motion))}$('motionButton').onclick=()=>{motion=!motion;localStorage.setItem('atlas-motion',motion?'on':'off');motionState()};motionState();function clock(){$('clock').textContent=new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit'}).format(new Date())+' · IST'}clock();setInterval(clock,30000);setInterval(()=>{if(!document.hidden)load()},60000);route();load();
