// Public data adapters. Successful empty responses are distinct from failed feeds.
const cache=new Map();
export const SPORT_NAMES=['MLB','NPB','KBO','ATP','WTA','NBA','NFL','NHL','Cricket','Soccer','Esports'];
export const todayIST=(now=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);
export const addDay=(date,n)=>new Date(Date.parse(date+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
export const inWindow=(date,day)=>{const t=Date.parse(date),a=Date.parse(day+'T00:00:00+05:30');return Number.isFinite(t)&&t>=a&&t<a+2*86400000};
export const clean=s=>String(s??'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&nbsp;/g,' ').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim();
export const safeURL=s=>{try{const u=new URL(s);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}};
export async function request(url,options={}){const r=await fetch(url,{...options,headers:{'User-Agent':'ATLAS personal research dashboard/0.2',...options.headers},signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(`Source returned HTTP ${r.status}`);return r}
const json=async(u,o)=>{try{return await(await request(u,o)).json()}catch(e){if(e instanceof SyntaxError)throw Error('Source returned an unsupported response');throw e}};
const source=(id,sport,name,url,official,features)=>({id,sport,name,url,official,features});
async function cachedSource(def,day,load){const key=def.id+day,old=cache.get(key);if(old&&Date.now()-old.checked<60000)return old.data;
 try{const payload=await load();const stamp=new Date().toISOString();const data={...def,status:'connected',checked_at:stamp,received_at:stamp,events:[],news:[],...payload};data.events=data.events.map(e=>({...e,source_id:def.id,source:def.name,source_url:e.source_url||def.url,official:def.official,received_at:stamp}));cache.set(key,{checked:Date.now(),data});return data}
 catch(e){const data={...def,status:old?.data.received_at?'stale':'unavailable',checked_at:new Date().toISOString(),received_at:old?.data.received_at||null,events:old?.data.events||[],news:old?.data.news||[],error:e.name==='TimeoutError'?'Source timed out':String(e.message).slice(0,150)};cache.set(key,{checked:Date.now(),data});return data}}
export function parseMLB(d){return(d.dates||[]).flatMap(day=>(day.games||[]).map(g=>({id:`mlb:${g.gamePk}`,external_id:String(g.gamePk),sport:'MLB',league:g.seriesDescription||'MLB',name:`${g.teams.away.team.name} @ ${g.teams.home.team.name}`,start:g.gameDate,state:g.status.abstractGameCode==='L'?'live':g.status.abstractGameCode==='F'?'finished':'scheduled',status:g.status.detailedState,venue:g.venue?.name,source_url:`https://www.mlb.com/gameday/${g.gamePk}`,competitors:['away','home'].map(side=>({name:g.teams[side].team.name,side,score:g.teams[side].score??null,record:g.teams[side].leagueRecord,starter:g.teams[side].probablePitcher?.fullName||null,starter_status:g.teams[side].probablePitcher?'probable':'unknown'})),notes:g.description?[g.description]:[],detail_kind:'mlb'})))}
export function parseNHL(d){return(d.gameWeek||[]).flatMap(day=>(day.games||[]).map(g=>({id:`nhl:${g.id}`,external_id:String(g.id),sport:'NHL',league:g.gameType===1?'NHL preseason':'NHL',name:`${g.awayTeam.placeName?.default||''} ${g.awayTeam.commonName?.default||g.awayTeam.abbrev} @ ${g.homeTeam.placeName?.default||''} ${g.homeTeam.commonName?.default||g.homeTeam.abbrev}`,start:g.startTimeUTC,state:['LIVE','CRIT'].includes(g.gameState)?'live':['FINAL','OFF'].includes(g.gameState)?'finished':'scheduled',status:g.gameState,venue:g.venue?.default,source_url:`https://www.nhl.com/gamecenter/${g.id}`,competitors:['away','home'].map(side=>({name:`${g[side+'Team'].placeName?.default||''} ${g[side+'Team'].commonName?.default||g[side+'Team'].abbrev}`.trim(),side,score:g[side+'Team'].score??null})),notes:[],detail_kind:'nhl'})))}
// ESPN's own odds line (a US sportsbook, usually DraftKings): moneyline and total, as decimal prices.
const decimalOdds=ml=>{const n=Number(String(ml??'').replace('EVEN','100'));return Number.isFinite(n)&&n!==0?+(n>0?1+n/100:1+100/-n).toFixed(2):null};
export function espnMarkets(c,teams){const o=c.odds?.[0];if(!o)return[];const side=s=>teams.find(t=>t.side===s)?.name;const m=[];const h=decimalOdds(o.homeTeamOdds?.moneyLine??o.moneyline?.home?.close?.odds),a=decimalOdds(o.awayTeamOdds?.moneyLine??o.moneyline?.away?.close?.odds),dr=decimalOdds(o.drawOdds?.moneyLine??o.moneyline?.draw?.close?.odds);
 if(h&&a&&side('home')&&side('away'))m.push({name:dr?'Match Result':'Winner',outcomes:[{name:side('home'),odds:h},...(dr?[{name:'Draw',odds:dr}]:[]),{name:side('away'),odds:a}]});
 const ov=decimalOdds(o.overOdds??o.total?.over?.close?.odds),un=decimalOdds(o.underOdds??o.total?.under?.close?.odds);if(o.overUnder&&ov&&un)m.push({name:`Total ${o.overUnder}`,outcomes:[{name:`Over ${o.overUnder}`,odds:ov},{name:`Under ${o.overUnder}`,odds:un}]});
 const sp=Number(o.spread??o.pointSpread?.home?.close?.line),sh=decimalOdds(o.homeTeamOdds?.spreadOdds??o.pointSpread?.home?.close?.odds),sa=decimalOdds(o.awayTeamOdds?.spreadOdds??o.pointSpread?.away?.close?.odds);
 if(Number.isFinite(sp)&&sp!==0&&sh&&sa&&side('home'))m.push({name:'Spread',line:sp,outcomes:[{name:`${side('home')} ${sp>0?'+':''}${sp}`,odds:sh},{name:`${side('away')} ${-sp>0?'+':''}${-sp}`,odds:sa}]});
 return m.length?[{bookmaker:o.provider?.name||'ESPN line',markets:m}]:[]}
export function parseESPN(d,sport,league){return(d.events||[]).flatMap(e=>{const comps=e.competitions||e.groupings?.filter(g=>sport==='ATP'?g.grouping?.slug?.startsWith('mens-'):sport==='WTA'?g.grouping?.slug?.startsWith('womens-'):true).flatMap(g=>g.competitions||[])||[];return comps.filter(c=>(c.competitors||[]).length>=2).map(c=>{const teams=c.competitors.map(t=>({name:t.team?.displayName||t.athlete?.displayName||t.team?.name||'TBA',side:t.homeAway,score:t.score&&typeof t.score==='object'?t.score.displayValue:(t.score??null),record:t.records?.find(r=>r.type==='total')?.summary||null,color:/^[0-9a-f]{6}$/i.test(t.team?.color||'')?'#'+t.team.color:null}));const status=c.status||e.status||{};return{id:`espn:${league}:${c.id}`,external_id:String(c.id),sport,league:e.name&&sport.match(/ATP|WTA/)?e.name:(d.leagues?.[0]?.name||league),name:teams.map(t=>t.name).join(' vs '),start:c.date||e.date,state:status.type?.state==='in'?'live':status.type?.completed?'finished':'scheduled',status:status.type?.shortDetail||status.type?.description||'Scheduled',venue:c.venue?.fullName,competitors:teams,source_url:safeURL(c.links?.[0]?.href||e.links?.[0]?.href)||`https://www.espn.com/${sport.toLowerCase()}/`,notes:[c.round?.displayName,...(c.notes||[]).map(n=>n.headline)].filter(Boolean),detail_kind:'espn',espn_path:league,form:Object.fromEntries(c.competitors.map(t=>[t.homeAway,t.form||null])),reference_odds:espnMarkets(c,teams)[0]||null}})})}
export function parseNPB(html,date){if(!html.includes('the_game_on_day'))throw Error('NPB page format changed');const blocks=[...html.matchAll(/<(a|span)\b[^>]*class="link_box"[^>]*>([\s\S]*?)<\/\1>/g)];return blocks.map((m,i)=>{const names=[...m[2].matchAll(/class="team_name"[^>]*>([\s\S]*?)<\/div>/g)].map(x=>clean(x[1]));if(names.length!==2)return null;const scores=[...m[2].matchAll(/class="score_text[^\"]*"[^>]*>([\s\S]*?)<\/div>/g)].map(x=>clean(x[1]));const round=clean(m[2].match(/class="round"[^>]*>([\s\S]*?)<\/div>/)?.[1]);const time=round.match(/\b(\d{1,2}:\d{2})\b/)?.[1];const href=m[0].match(/href="([^"]+)"/)?.[1];return{id:`npb:${date}:${i}`,sport:'NPB',league:'NPB',name:names.join(' vs '),start:time?new Date(`${date}T${time.padStart(5,'0')}:00+09:00`).toISOString():null,date,has_exact_time:!!time,state:scores.every(s=>/^\d+$/.test(s))?'finished':'scheduled',status:round||'Schedule published',venue:round.replace(/\d{1,2}:\d{2}/,''),competitors:names.map((name,j)=>({name,score:scores[j]||null,side:j?'away':'home'})),notes:['Official NPB schedule; lineups not included in this feed.'],source_url:href?new URL(href,'https://npb.jp').href:`https://npb.jp/bis/eng/${date.slice(0,4)}/games/gm${date.replaceAll('-','')}.html`}}).filter(Boolean)}
export function parseRSS(xml,def){if(!/<rss|<feed/i.test(xml))throw Error('Source did not return a news feed');return[...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].slice(0,15).map((m,i)=>{const tag=n=>clean(m[1].match(new RegExp(`<${n}[^>]*>([\\s\\S]*?)<\\/${n}>`,'i'))?.[1]);return{id:`${def.id}:${i}`,title:tag('title'),url:safeURL(tag('link')),published_at:tag('pubDate')&&Number.isFinite(Date.parse(tag('pubDate')))?new Date(tag('pubDate')).toISOString():null,sport:def.sport,source:def.name,official:def.official}}).filter(n=>n.title&&n.url)}
const ESPN=[['NBA','basketball/nba'],['NFL','football/nfl'],['ATP','tennis/atp'],['WTA','tennis/wta'],['Soccer','soccer/eng.1'],['Soccer','soccer/esp.1'],['Soccer','soccer/ger.1'],['Soccer','soccer/ita.1'],['Soccer','soccer/fra.1'],['Soccer','soccer/uefa.champions'],['Soccer','soccer/uefa.nations'],['Soccer','soccer/eng.2'],['Soccer','soccer/ned.1'],['Soccer','soccer/por.1'],['Soccer','soccer/sco.1'],['Soccer','soccer/tur.1'],['Soccer','soccer/bel.1'],['Soccer','soccer/bra.1'],['Soccer','soccer/arg.1'],['Soccer','soccer/mex.1'],['Soccer','soccer/usa.1'],['Soccer','soccer/ksa.1'],['Soccer','soccer/jpn.1'],['Soccer','soccer/uefa.europa'],['Soccer','soccer/uefa.europa.conf'],['Soccer','soccer/conmebol.libertadores'],['NBA','basketball/wnba']];
const RSS=[source('bbc-soccer','Soccer','BBC Sport','https://feeds.bbci.co.uk/sport/football/rss.xml',false,['headlines']),source('bbc-cricket','Cricket','BBC Sport','https://feeds.bbci.co.uk/sport/cricket/rss.xml',false,['headlines']),source('bbc-tennis','ATP','BBC Sport','https://feeds.bbci.co.uk/sport/tennis/rss.xml',false,['headlines']),source('bbc-nfl','NFL','BBC Sport','https://feeds.bbci.co.uk/sport/american-football/rss.xml',false,['headlines']),source('steam-dota','Esports','Dota 2 / Valve','https://store.steampowered.com/feeds/news/app/570/?l=english',true,['patches','official news']),source('steam-cs','Esports','Counter-Strike 2 / Valve','https://store.steampowered.com/feeds/news/app/730/?l=english',true,['patches','official news'])];
export async function loadFeeds(day=todayIST()){
 const jobs=[];
 jobs.push(cachedSource(source('mlb','MLB','MLB official','https://www.mlb.com/scores',true,['schedule','scores','probable pitchers','lineups on demand']),day,async()=>({events:parseMLB(await json(`https://statsapi.mlb.com/api/v1/schedule?sportId=1&startDate=${addDay(day,-1)}&endDate=${addDay(day,1)}&hydrate=probablePitcher,team`))})));
 jobs.push(cachedSource(source('nhl','NHL','NHL official','https://www.nhl.com/scores',true,['schedule','scores','box scores on demand']),day,async()=>({events:parseNHL(await json(`https://api-web.nhle.com/v1/schedule/${addDay(day,-1)}`))})));
 jobs.push(cachedSource(source('npb','NPB','NPB official','https://npb.jp/bis/eng/',true,['schedule','scores']),day,async()=>{const results=await Promise.allSettled([day,addDay(day,1)].map(async date=>parseNPB(await(await request(`https://npb.jp/bis/eng/${date.slice(0,4)}/games/gm${date.replaceAll('-','')}.html`)).text(),date)));const ok=results.filter(r=>r.status==='fulfilled');if(!ok.length)throw results[0].reason;return{events:ok.flatMap(r=>r.value),partial:ok.length<2}}));
 jobs.push(cachedSource(source('kbo','KBO','KBO official','https://www.koreabaseball.com/Schedule/GameCenter/Main.aspx',true,['schedule','scores','starting pitchers when supplied']),day,async()=>{const results=await Promise.all([day,addDay(day,1)].map(date=>json('https://www.koreabaseball.com/ws/Main.asmx/GetKboGameList',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({leId:'1',srId:'0,1,3,4,5,6,7,8,9',date:date.replaceAll('-','')})})));if(!results.every(d=>Array.isArray(d.game)))throw Error('KBO schedule format unavailable');return{events:results.flatMap((d,i)=>d.game.map(g=>({id:`kbo:${g.G_ID}`,sport:'KBO',league:'KBO',name:`${g.AWAY_NM||g.AWAY_ID} vs ${g.HOME_NM||g.HOME_ID}`,start:g.G_DT&&g.G_TM?new Date(`${day}T${g.G_TM}:00+09:00`).toISOString():null,date:addDay(day,i),state:'scheduled',status:g.GAME_STATE||'Source schedule',competitors:[],notes:[]})))}}));
 for(const[sport,path]of ESPN)jobs.push(cachedSource(source(`espn-${path.replace('/','-')}`,sport,`ESPN · ${path.split('/')[1].toUpperCase()}`,`https://www.espn.com/${sport==='Soccer'?'soccer':sport.toLowerCase()}/`,false,['schedule','scores','records']),day,async()=>{const ds=[addDay(day,-1),day,addDay(day,1)];const replies=await Promise.allSettled(ds.map(date=>json(`https://site.api.espn.com/apis/site/v2/sports/${path}/scoreboard?dates=${date.replaceAll('-','')}`).then(d=>parseESPN(d,sport,path))));const ok=replies.filter(r=>r.status==='fulfilled');if(!ok.length)throw replies[0].reason;return{events:ok.flatMap(r=>r.value),partial:ok.length<ds.length}}));
 const cric=source('cricinfo','Cricket','ESPNcricinfo live scores','https://static.espncricinfo.com/rss/livescores.xml',false,['current score summaries']);
 jobs.push(cachedSource(cric,day,async()=>{const xml=await(await request(cric.url)).text();const published=clean(xml.match(/<pubDate>(.*?)<\/pubDate>/)?.[1]);return{events:parseRSS(xml,cric).map((n,i)=>({id:`cricket:${i}:${n.url}`,sport:'Cricket',league:'ESPNcricinfo',name:n.title,start:null,date:day,state:'score-update',status:'Current score summary',competitors:[],notes:['The score feed does not establish match start time or lineup confirmation.'],source_url:n.url,source_updated_at:published||null}))}}));
 for(const def of RSS)jobs.push(cachedSource(def,day,async()=>({news:parseRSS(await(await request(def.url)).text(),def)})));
 const data=await Promise.all(jobs);const eventMap=new Map();for(const s of data)for(const e of s.events)if(e.start?inWindow(e.start,day):[day,addDay(day,1)].includes(e.date))eventMap.set(e.id,{...e,feed_status:s.status});
 const events=[...eventMap.values()].sort((a,b)=>(Date.parse(a.start)||Infinity)-(Date.parse(b.start)||Infinity));
 const sources=data.map(({events,news,...s})=>({...s,event_count:new Set(events.filter(e=>eventMap.has(e.id)).map(e=>e.id)).size,news_count:news.length}));
 sources.push({id:'esports-fixtures',sport:'Esports',name:'Tournament fixture feed',url:'https://lolesports.com/',official:false,status:'not-connected',features:['fixtures'],event_count:0,news_count:0,error:'No authenticated tournament fixture provider configured.'});
 return{generated_at:new Date().toISOString(),day,timezone:'Asia/Kolkata',window_end:addDay(day,1),refresh_seconds:60,events,sources,news:data.flatMap(s=>s.news.map(n=>({...n,feed_status:s.status,received_at:s.received_at}))).sort((a,b)=>(Date.parse(b.published_at)||0)-(Date.parse(a.published_at)||0)).slice(0,70)};
}
export async function eventDetail(event){
 if(event.detail_kind==='mlb'){const d=await json(`https://statsapi.mlb.com/api/v1.1/game/${event.external_id}/feed/live`);const teams=d.liveData?.boxscore?.teams||{};const lineups=['away','home'].map(side=>{const t=teams[side]||{};return{team:event.competitors.find(c=>c.side===side)?.name,players:(t.battingOrder||[]).map(id=>t.players?.['ID'+id]?.person?.fullName).filter(Boolean),status:(t.battingOrder||[]).length?'Published batting order':'Not published'}});return{lineups,weather:d.gameData?.weather||null,probable_pitchers:d.gameData?.probablePitchers||{},source_url:event.source_url,received_at:new Date().toISOString(),notes:['Published batting orders can change before first pitch.']}}
 if(event.detail_kind==='nhl'){const d=await json(`https://api-web.nhle.com/v1/gamecenter/${event.external_id}/landing`);return{summary:d.summary||{},source_url:event.source_url,received_at:new Date().toISOString(),notes:['Goalie confirmation and scratches require a separate team report.']}}
 if(event.detail_kind==='espn'){const d=await json(`https://site.api.espn.com/apis/site/v2/sports/${event.espn_path}/summary?event=${event.external_id}`);return{injuries:d.injuries||[],rosters:d.rosters||[],source_url:event.source_url,received_at:new Date().toISOString(),notes:['An empty injury or roster response means unavailable, not injury-free.']}}
 return{source_url:event.source_url,notes:['Detailed lineups are not supplied by this adapter. Open the source to check.']};
}
